name: ci
on: push
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Test 📦
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6

      - name: Semantic Release 🚀
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
